---
title: "Getting and Cleaning Data Quiz 4"
author: Xinchun Tian
output: html_document
---

## Questioin 1.
```{r}
library(data.table)
url <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv"
if (!file.exists("ss06hid.csv")) {
    download.file(url, destfile = "/Users/tianxc/repo/git/data_science/Getting_and_Cleaning_Data/Quiz/ss06hid.csv", method="curl")
}
dt <- read.table("ss06hid.csv", sep = ",", header = TRUE)
head(dt)
strsplit(names(dt),"wgtp")[[123]]
```

## Question 2.
```{r}
url <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv"
if (!file.exists("GDP.csv")) {
    download.file(url, destfile = "/Users/tianxc/repo/git/data_science/Getting_and_Cleaning_Data/Quiz/GDP.csv", method="curl")
}
gdp <- read.csv("GDP.csv", na.strings = "")
gdp_dollars <- sapply(gdp$X.3[5:194], function(x) gsub(",","",x))
mean(as.numeric(gdp_dollars))
```

## Question 3.
```{r}
length(grep("^United", gdp$X.2))
```

## Question 4.
```{r}
library(plyr)
url <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv"
if (!file.exists("EDSTATS_Country.csv")) {
    download.file(url, destfile = "/Users/tianxc/repo/git/data_science/Getting_and_Cleaning_Data/Quiz/EDSTATS_Country.csv", method="curl")
}
gdp <- read.csv("GDP.csv", sep=",", na.strings = "")
edu <- read.csv("EDSTATS_Country.csv", sep=",", na.strings = "")
gdp <- gdp[5:194,]
gdp <- rename(gdp, c("X" = "CountryCode"))
merged <- merge(gdp, edu, by="CountryCode")
merged$Gross.domestic.product.2012 <- as.numeric(as.character(merged$Gross.domestic.product.2012))
merged <- merged[order(merged$Gross.domestic.product.2012,decreasing = TRUE),]
str(merged)
grep("Fiscal year end: June", merged[,19], value = TRUE)
```

## Question 5.
```{r}
library(quantmod)
amzn = getSymbols("AMZN",auto.assign=FALSE)
sampleTimes = index(amzn) 
sampleTimes <- sampleTimes[as.POSIXlt(as.Date(sampleTimes))$year+1900=="2012"]
length(sampleTimes)
length(sampleTimes[weekdays(as.Date(sampleTimes))=="Monday"])
```
